### ISSUE TITLE
missing config?

### ISSUE THREAD

**Issue by PhilippeBach** [KtreeOpenSource/KTree_Odoo-Magento-Connector#1]
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 567, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 796, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 939, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 927, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/custom/addons/ktree_magento_connector/wizard/magento_categories_import.py", line 23, in do_categories_import
    raise osv.except_osv(('Warning'), ('Import failed, please refer to configure file for failure details.'))
except_orm: ('Warning', 'Import failed, please refer to configure file for failure details.')

impossible to connect  tu the magento

**Comment by KtreeOpenSource** [comment]
Hi Philippe

Please reconfirm you have followed all the steps as per the release notes.
We suspect based on the log you have sent the module has not been installed on the Magento side.

GENERAL USAGE NOTES :
- The ktree_magento_connector module is build with the help of the source codes available in lunchpad, github.
- The KTree Magento Connector for Odoo 8 will be based on the OpenERP Magento Connector for OpenERP 7 and will have the following core features:
  
  Compatible with Odoo 8 and the Magento versions 1.7 or later
  Synchronization of customers, products, sales orders, invoices, payment status, product stock, Delivery status;
  Magento import/Export products supported: simple, bundle products.
- This module is having a dependency on product_images_olbs which is available on odoo apps.
- Magento side we have created a new custom API which is more flexible for synchronization process between the magento and odoo..
- Magento custom API Ktree_Customapi-0.1.0.tgz which needs to be installed at magento side before proceeding for Synchronization.
- Place the ktree_magento_connector module in odoo 8 addons and install it.
- create a API user at magento with all role based access rights.
- Configure the magento api details on odoo under the menu called  Magento--> Magento settings.

Thanks
KTree

**Comment by PhilippeBach** [comment]
I install all like the that manual install Ktree_Customapi because no Ktree_Customapi.tgz on github 

Sincerly

**Comment by KtreeOpenSource** [comment]
Hi Philippe

Please find the Ktree_Customapi.tgz uploaded in the branch.
Please follow the release notes steps and let us know if any queries.

thanks
KTree

**Comment by PhilippeBach** [comment]
Reinstalled brand new openerp connected to my magento 

and i have those problems 

2015-04-16 21:23:51,667 26169 ERROR sf openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 567, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 796, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 940, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/custom/addons/ktree_magento_connector/wizard/magento_categories_import.py", line 23, in do_categories_import
    raise osv.except_osv(('Warning'), ('Import failed, please refer to configure file for failure details.'))
except_orm: ('Warning', 'Import failed, please refer to configure file for failure details.')

Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 567, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 796, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 940, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/custom/addons/ktree_magento_connector/wizard/magento_categories_import.py", line 23, in do_categories_import
    raise osv.except_osv(('Warning'), ('Import failed, please refer to configure file for failure details.'))
except_orm: ('Warning', 'Import failed, please refer to configure file for failure details.')

Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 567, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 796, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 940, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/custom/addons/ktree_magento_connector/wizard/magento_categories_import.py", line 23, in do_categories_import
    raise osv.except_osv(('Warning'), ('Import failed, please refer to configure file for failure details.'))
except_orm: ('Warning', 'Import failed, please refer to configure file for failure details.')

Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 567, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 796, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 940, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/custom/addons/ktree_magento_connector/wizard/magento_categories_import.py", line 23, in do_categories_import
    raise osv.except_osv(('Warning'), ('Import failed, please refer to configure file for failure details.'))
except_orm: ('Warning', 'Import failed, please refer to configure file for failure details.')

Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 567, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 796, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 940, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/custom/addons/ktree_magento_connector/wizard/magento_customer_import.py", line 14, in do_customers_import
    result=self.pool.get('magento.configuration').import_customers(cr, uid)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/custom/addons/ktree_magento_connector/partner_configuration.py", line 450, in import_customers
    cust_ids = [self.pool.get('res.partner').create(cr, uid, erp_customer)]
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 336, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/res/res_partner.py", line 573, in create
    partner = super(res_partner, self).create(vals)
  File "/opt/odoo/odoo-server/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/opt/odoo/odoo-server/addons/mail/mail_thread.py", line 384, in create
    thread_id = super(mail_thread, self).create(cr, uid, values, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 336, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 4059, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/odoo-server/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 4231, in _create
    recs.modified(self._fields)
TypeError: 'bool' object is not callable

regards Philippe

**Comment by KtreeOpenSource** [comment]
Hi Philippe,

please check the configuration object under the menu Magento--> Magento settings.

The first possibility of the issue is missing the configuration..
And the second one is, there may be no connection established with the magento server..
and next is the api plugin installing at magento side.

if possible please send the screen shot of Magento - > Import from Magento -> Magento Settings.

Thanks
KTree
